# Generated by Django 5.2.8 on 2025-11-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='s3_key',
            new_name='local_path',
        ),
    ]
