# Generated by Django 5.2.8 on 2025-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_rename_s3_key_video_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
