# Generated by Django 5.2.8 on 2025-11-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_video_media_type_video_thumbnail_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
    ]
