# Generated by Django 5.2.8 on 2025-11-14 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_video_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('user', 'title')},
        ),
    ]
